# Generated by Django 2.2.7 on 2019-12-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True)),
                ('loan_period', models.IntegerField(blank=True, default=0.0, null=True)),
                ('loan_status', models.BooleanField(default=False)),
                ('loan_installment_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True)),
                ('loan_interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True)),
                ('net_payable_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=30, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.BankCustomer')),
            ],
        ),
    ]
